title: Portfolio
description: Alexander Kucheryuk Portfolio
baseurl: "/portfolio-new"
url: "https://alexkuc.github.io"
permalink: pretty

heading_anchors: true
footer_content: Alexander Kucheryuk Portfolio

remote_theme: pmarsceill/just-the-docs
color_scheme: nil

search_enabled: false

aux_links:
  "GitHub":
    - "https://github.com/alexkuc/"
  "LinkedIn":
    - "https://www.linkedin.com/in/alexkuc/"
  "AngelCo":
    - "https://angel.co/u/alexkuc/"
  "Upwork":
    - "https://www.upwork.com/freelancers/~01948e7d9c3eb9505a/"

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

ga_tracking: UA-157973764-1
